<?php
/**
 * Created by PhpStorm.
 * User: dasha
 * Date: 29.12.18
 * Time: 18:10
 */

namespace app\controllers;

use app\models\ActionsModel;
use app\models\BoatsModel;
use app\models\OrderConfirmForm;
use app\models\OrderCreateForm;
use app\models\OrdersModel;
use app\models\PayForm;
use app\models\PromoModel;
use app\models\ServicesModel;
use DateInterval;
use DatePeriod;
use DateTime;
use Yii;
use yii\base\Exception;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;

class OrderController extends Controller
{
    public $order;

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['create', 'confirm-step1', 'confirm-step2', 'apply-promo', 'add-service',
                                      'remove-service', 'info', 'get-times', 'final', 'refund', 'price', 'get-dates', 'refund-modal'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    public function beforeAction($action)
    {
        if ($action->id == 'confirm-step1' || $action->id == 'confirm-step2') {
            $this->order = OrdersModel::findOne(Yii::$app->request->get('id'));
            if (Yii::$app->user->getId() != $this->order->user_id) throw new ForbiddenHttpException('Чужой заказ!');
            if ($this->order->state != 0) throw new Exception('Заказ находится в некорректном статусе!');
        }

        if ($action->id == 'final') {
            $this->order = OrdersModel::findOne(Yii::$app->request->get('id'));
            if (Yii::$app->user->getId() != $this->order->user_id) throw new ForbiddenHttpException('Чужой заказ!');
        }

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionCreate() {
        $post = Yii::$app->request->post();
        $form = new OrderCreateForm();

        $form->load($post);
        $form->user_id = Yii::$app->user->getId();

        Yii::info('Попытка создания заказа ['.json_encode($form).']', 'app.order.create');

        if($form->validate()) {
            $order = $form->save();
            return $this->redirect(['/order/confirm-step1', 'id' => $order->id]);
        }

        Yii::error('Заказ не создан ['.json_encode($form->getErrors()).']', 'app.order.create');
        return $this->redirect(Yii::$app->request->referrer);
    }

    public function actionConfirmStep1(int $id) {
        $order = $this->order;

        $model = new OrderConfirmForm();
        $post = Yii::$app->request->post();
        $model->user_id = Yii::$app->user->getId();

        if ($post) {
            Yii::info('Подтверждение заказа ['.json_encode($post).']', 'app.order.step1');
            $model->load($post);

            if ($model->validate()) {
                $order->price = $model->coast;
                $order->datetime_from = $model->datetime_from;
                $order->datetime_to = $model->datetime_to;
                $order->count_hours = count($this->getDateTimeInterval($model->datetime_from, $model->datetime_to));
                $order->save();
                return $this->redirect(['/order/confirm-step2', 'id' => $order->id]);
            }

            Yii::error('Ошибка формирования заказа ['.json_encode($model->getErrors()).']', 'app.order.step1');
        }

        return $this->render('confirm-step1', compact('order', 'model'));
    }

    public function actionConfirmStep2(int $id) {
        $order = $this->order;

        $services = $order->boat->services;
        $model = new PayForm();

        return $this->render('confirm-step2', compact('order', 'services', 'model'));
    }

    /*
     * Страница успешной оплаты
     */
    public function actionFinal(int $id) {

        $order = $this->order;
        $model = new PayForm();

        return $this->render('final', compact('order', 'model'));
    }

    /**
     * Отмена заказа и возврат денег
     * @param int $id
     * @return \yii\web\Response
     * @throws \CloudPayments\Exception\RequestException
     */
    public function actionRefund(int $id) {

        $order = OrdersModel::findOne($id);
        try {
            if (Yii::$app->user->identity->isAdmin()) {
                $money = $order->transaction->total_price;
            } else {
                $money = $order->transaction->total_price - $order->transaction->fine();
                if (!$money) throw new Exception('Не удалось расчитать сумму возврата.');
            }

            $client = new \CloudPayments\Manager(Yii::$app->params['cloud_id'], Yii::$app->params['cloud_private_key']);
            $client->refundPayment($order->transaction->cloud_transaction_id, $money);
        } catch (Exception $e){
            Yii::error($e->getMessage(), 'app.order.refund');
            return $this->asJson(['result' => false]);
        }

        $order->state = 2;
        $order->save();

        $order->transaction->state = 2;
        $order->transaction->refund_price = $money;
        $order->transaction->save();

        Yii::info("Order [$id] success refund", 'app.order.refund');
        return $this->asJson(['result' => true]);
    }

    /**
     * Применение промокода
     * @param int $order_id
     * @param string $word
     * @return bool
     */
    public function actionApplyPromo(int $order_id, string $word) {

        Yii::info("Apply Promo: $word", 'app.order.apply-promo');

        try {
            $promocode = PromoModel::find()->where(['word' => trim($word), 'is_active' => 1])->one();
            if (!$promocode) throw new Exception('Промокод не найден!');
        } catch (Exception $e) {
            Yii::$app->session->setFlash("order-error", $e->getMessage());
            Yii::error($e->getMessage(), 'app.order.apply-promo');
            return false;
        }

        try {
            $order = OrdersModel::findOne($order_id);
            $order->applyPromo($promocode);
        } catch (Exception $e) {
            Yii::$app->session->setFlash("order-error", 'Не удалось применить промокод.');
            Yii::error($e->getMessage(), 'app.order.apply-promo');
            return false;
        }

        return true;
    }

    /**
     * Добавление доп.услуг
     * @param int $order_id
     * @param int $service_id
     * @return bool|string
     */
    public function actionAddService(int $order_id, int $service_id) {
        try {
            $order = OrdersModel::findOne($order_id);
            $service = ServicesModel::findOne($service_id);

            $order->link('services', $service);
        } catch (Exception $e) {
            Yii::error($e->getMessage(), 'app.order.add-service');
            Yii::$app->session->setFlash("order-error", 'Не удалось добавить услугу.');
            return false;
        }

        return $this->renderPartial('_payBlock', compact('order'));   ;
    }

    /*
     * Удаление доп.услуг
     */
    public function actionRemoveService(int $order_id, int $service_id) {
        try {
            $order = OrdersModel::findOne($order_id);
            $service = ServicesModel::findOne($service_id);

            $order->unlink('services', $service);
        } catch (Exception $e) {
            Yii::error($e->getMessage(), 'app.order.remove-service');
            Yii::$app->session->setFlash("order-error", 'Не удалось удалить услугу.');
            return false;
        }

        return $this->renderPartial('_payBlock', compact('order'));
    }

    public function actionInfo($id) {
        $order = OrdersModel::findOne($id);

        if (Yii::$app->user->getId() != $order->user_id) throw new ForbiddenHttpException('Чужой заказ!');

        return $this->renderPartial('_orderInfo', compact('order'));
    }

    public function actionRefundModal(int $id) {

        Yii::info("Попытка вернуть заказ [$id]", 'app.order.refund-modal');
        try {
            $order = OrdersModel::findOne($id);
            if (!$order) throw new Exception('Заказ не найден.');

            $money = $order->transaction->fine();
            if (!$money) throw new Exception('Не удалось расчитать сумму возврата.');
        } catch (Exception $e) {
            Yii::error("Попытка вернуть заказ [$id]:". $e->getMessage(), 'app.order.refund-modal');
        }

        return $this->renderPartial('_orderRefund', compact('order', 'money'));
    }

    /**
     * Достаем занятое время у каждой лодки
     * @param int $boat_id
     * @param $date
     * @return \yii\web\Response
     * @throws \Exception
     */
    public function actionGetTimes(int $boat_id, $date) {

        $date1 = new DateTime($date.'-01');
        $date2 = new DateTime($date.'-01');
        $busyBoats = OrdersModel::find()
                            ->where(['boat_id' => $boat_id, 'state' => [1,3]])
                            ->andWhere(['>=', 'datetime_from', $date1->format('Y-m-d')])
                            ->andWhere(['<=',  'datetime_from', $date1->modify('+ 1 month')->format('Y-m-d')])
                            ->all();
        $datetimes = [];
        foreach ($busyBoats as &$busyBoat) {
            $begin = new DateTime($busyBoat->datetime_from);
            $end = new DateTime( $busyBoat->datetime_to);
            $interval = new DateInterval('PT1H');
            $range = new DatePeriod($begin, $interval ,$end);
            foreach ($range as $rng) {
                $datetimes[] = $rng->format('Y-m-d\TH:00:00');
            }
        }

        $actions = ActionsModel::find()->joinWith('boat')->where(['boat_id' => $boat_id])->andWhere(['>=', 'datetime_from', $date2->format('Y-m-d')])
            ->andWhere(['<=',  'datetime_from', $date2->modify('+ 1 month')->format('Y-m-d')])->all();

        $datetimes2 = [];
        foreach ($actions as &$action) {
            $begin = new DateTime($action->datetime_from);
            $end = new DateTime( $action->datetime_to);
            $interval = new DateInterval('PT1H');
            $range = new DatePeriod($begin, $interval ,$end);
            foreach ($range as $rng) {
                $datetimes2[] = $rng->format('Y-m-d\TH:00:00');
            }
        }

        return $this->asJson(['calendar' => $datetimes,
                               'actions' => $datetimes2
        ]);
    }

    public function actionGetDates(int $boat_id, $date) {

        $firstMonthDay = new DateTime($date);
        $cloneFirstMonthDay = clone $firstMonthDay;

        $lastMonthDay = $firstMonthDay->modify('+ 1 month');

        $busyBoats = OrdersModel::find()
            ->where(['boat_id' => $boat_id, 'state' => [1,3]])
            ->andWhere(['>=', 'datetime_from', $cloneFirstMonthDay->format('Y-m-d')])
            ->andWhere(['<=',  'datetime_from', $lastMonthDay->format('Y-m-d')])
            ->all();

        $period = new DatePeriod(
            $cloneFirstMonthDay,
            new DateInterval('P1D'),
            $lastMonthDay
        );

        foreach ($period as $key => $value) {
            $dates[] = $value->format('Y-m-d');
        }

        $datescnt = [];
        foreach ($dates as $date) {
            foreach ($busyBoats as &$busyBoat) {
                $begin = new DateTime($busyBoat->datetime_from);
                $end = new DateTime($busyBoat->datetime_to);
                if ($date >= $begin->format('Y-m-d') and $date <= $end->format('Y-m-d'))
                    $datescnt[$date] = $busyBoat->count_hours;
            }
        }

        $actions = ActionsModel::find()->joinWith('boat')
            ->where(['boat_id' => $boat_id])
            ->andWhere(['>=', 'datetime_from', $cloneFirstMonthDay->format('Y-m-d')])
            ->andWhere(['<=',  'datetime_from', $lastMonthDay->format('Y-m-d')])
            ->all();

        $datescnt2 = [];
        foreach ($dates as $date) {
            foreach ($actions as &$action) {
                $begin = new DateTime($action->datetime_from);
                $end = new DateTime( $action->datetime_to);
                if ($date >= $begin->format('Y-m-d') and $date <= $end->format('Y-m-d')) {
                    $datescnt2[$date] = 1;
                }
            }
        }

        return $this->asJson(['dates' => $datescnt, 'actions' => $datescnt2]);
    }

    /**
     * Расчет стоимости заказа
     * @param int $boat_id
     * @param $datetime_from
     * @param $datetime_to
     * @return \yii\web\Response
     */
    public function actionPrice(int $boat_id, $datetime_from, $datetime_to) {

        try {
            $boat = BoatsModel::findOne($boat_id);
            if (empty($boat)) throw new Exception('Лодка не найдена!');

            $price = 0;

            $tariff = $boat->tariff;
            $datetimes = $this->getDateTimeInterval($datetime_from, $datetime_to);

            // TODO поправить
            $actions = $boat->getActions()->all();
            if (!empty($actions)) {
                $datetimes2 = $this->getDateTimeInterval($datetime_from, $datetime_to, 0);
                foreach ($datetimes2  as $dt) {
                    foreach ($actions as $action) {
                        $flag = 0;
                        $actt = $this->getDateTimeInterval($action->datetime_from, $action->datetime_to, 0);
                        foreach ($actt as $a) {
                            if ($a == $dt) {
                                $price += $action->price;
                                $flag = 1;
                            }
                        }
                    }
                    if ($flag == 0) {
                        $ti = new DateTime($dt);
                        if (count($datetimes2) >= 24) $price += $tariff->one_day;
                        elseif (count($datetimes2) >= 4) {
                            if (in_array($ti->format('D'), ['Sat', 'Sun'])) $price += $tariff->four_hours_holiday;
                            else $price += $tariff->four_hours_weekday;
                        }
                        elseif (in_array($ti->format('D'), ['Sat', 'Sun'])) $price += $tariff->holiday;
                        elseif (in_array($ti->format('d-m'), ['01-05', '02-05', '03-05', '09-05', '10-05', '12-06'])) $price += $tariff->holiday;
                        else $price += $tariff->weekday;
                    }
                }
            } else {
                if (count($datetimes) >= 24) $price = $tariff->one_day;
                elseif (count($datetimes) >= 4) {
                    if (in_array($datetimes[0]->format('D'), ['Sat', 'Sun'])) $price += $tariff->four_hours_holiday;
                    else $price += $tariff->four_hours_weekday;
                }
                elseif (in_array($datetimes[0]->format('D'), ['Sat', 'Sun'])) $price = $tariff->holiday;
                elseif (in_array($datetimes[0]->format('d-m'), ['01-05', '02-05', '03-05', '09-05', '10-05', '12-06'])) $price += $tariff->holiday;
                else $price = $tariff->weekday;
                $price = $price*count($datetimes);
            }
        } catch (Exception $e) {
            Yii::error("Произошла ошибка при расчете тарифа boat_i[$boat_id]", 'app.order.price');

            return $this->asJson([
                'success' => false
            ]);
        }

        return $this->asJson([
           'success' => true,
           'result' => $price
        ]);
    }

    private function getDateTimeInterval($datetime_from, $datetime_to, $raw = 1) {
        $begin = new DateTime($datetime_from);
        $end = new DateTime($datetime_to);
        $interval = new DateInterval('PT1H');
        $range = new DatePeriod($begin, $interval ,$end);
        foreach ($range as $rng) {
            $datetimes[] = ($raw)?$rng:$rng->format('Y-m-d\TH:00:00');
        }

        return $datetimes;
    }
}